language: python

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

env:
  global:
    - ICE=Ice-3.5.1-b1-ubuntu1204-amd64
  matrix:
    - OMERO_VERSION=5.1
    - OMERO_VERSION=5.2

before_install:
  - mkdir -p download
  - cd download
  - wget "http://downloads.openmicroscopy.org/ice/experimental/${ICE}.tar.xz"
  - cd ..
  - tar -xvf "download/${ICE}.tar.xz"
  - ICE_HOME="$(pwd)/${ICE}"
  - export SLICEPATH="${ICE_HOME}/slice"
  - export PATH="${ICE_HOME}/bin:$PATH"
  - export LD_LIBRARY_PATH="${ICE_HOME}/lib:$LD_LIBRARY_PATH"
  - export PYTHONPATH="${ICE_HOME}/python:$PYTHONPATH"
  - pip install omego pytest


install:
    - omego download --release OMERO_VERSION py

script:
    - PYTHONPATH=$PYTHONPATH:~/OMERO.py/lib/python py.test tests/unit
