language: python

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
     - zeroc-ice34

env:
  global:
    - ICE=Ice-3.5.1-b1-ubuntu1204-amd64
  matrix:
    - OMERO_VERSION=5.1
    - OMERO_VERSION=5.2

before_install:
  - wget http://downloads.openmicroscopy.org/ice/experimental/${ICE}.tar.xz
  - tar -xvf ${ICE}.tar.xz
  - pip install omego pytest flake8

install:
    - omego download --release ${OMERO_VERSION} py
    - rm OMERO.py*.zip
    - mv OMERO.py* OMERO.py

script:
    - flake8 .
    - LD_LIBRARY_PATH=./${ICE}/lib PYTHONPATH=./${ICE}/python:./OMERO.py/lib/python:. py.test tests/unit
